# Generated by Django 3.1.4 on 2021-01-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='user_id',
            new_name='user',
        ),
    ]
