# Generated by Django 3.1.4 on 2021-01-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='title',
        ),
    ]
