# Generated by Django 3.1.4 on 2021-01-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20210128_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='nameTable',
        ),
        migrations.AddField(
            model_name='word',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
