# Generated by Django 3.1.4 on 2021-01-29 20:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210128_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='inverosimil_relation',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
